BASE_IMAGE_URL = "https://cdn.jsdelivr.net/gh/Reeflex-M/cdn-carte/"
SPLASH_SOLITAIRE = "solitaire/splash.png"
SPLASH_BATAILLE = "bataille-52/splash.png"
SPLASH_POKEMON = "pokemon/splash.png"
SPLASH_ORIFLAMME = "oriflamme/splash.png"
SPLASH_MORPION = "morpion/splash.png"