# Generated by Django 5.0.1 on 2024-01-18 15:06

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carte', models.IntegerField()),
                ('type_jeu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nbr_victoire', models.IntegerField(default=0)),
                ('nbr_defaites', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MoteurDeJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('couleur', models.CharField(max_length=20)),
                ('TypeCarte', models.CharField(max_length=20)),
                ('NomCarte', models.CharField(max_length=20)),
                ('est_visible', models.BooleanField(default=False)),
                ('moteur_de_jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.moteurdejeu')),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=200)),
                ('chat_messages', models.ManyToManyField(to='battle.chat')),
                ('joueurs', models.ManyToManyField(to='battle.joueur')),
                ('moteur_de_jeu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.moteurdejeu')),
            ],
        ),
    ]
