# Generated by Django 5.0.1 on 2024-01-31 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('couleur', models.CharField(max_length=20)),
                ('TypeCarte', models.CharField(max_length=20)),
                ('NomCarte', models.CharField(max_length=20)),
                ('front_image_path', models.CharField(max_length=200)),
                ('back_image_path', models.CharField(max_length=200)),
                ('est_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoteurDeJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nbr_victoire', models.IntegerField(default=0)),
                ('nbr_defaites', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('user', models.OneToOneField(db_column='user_ptr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carte', models.IntegerField()),
                ('cartes', models.ManyToManyField(to='battle.carte')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='battle.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=200)),
                ('chat_messages', models.ManyToManyField(to='battle.chat')),
                ('decks', models.ManyToManyField(to='battle.deck')),
                ('moteur_de_jeu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.moteurdejeu')),
            ],
        ),
        migrations.CreateModel(
            name='PartieJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_inscription', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.joueur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.partie')),
            ],
        ),
        migrations.AddField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(through='battle.PartieJoueur', to='battle.joueur'),
        ),
        migrations.CreateModel(
            name='TypeJeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('path_splash', models.CharField(max_length=200)),
                ('moteurs_de_jeu', models.ManyToManyField(to='battle.moteurdejeu')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='type_jeu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.typejeux'),
        ),
        migrations.AddField(
            model_name='carte',
            name='TypeJeux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.typejeux'),
        ),
    ]
