# Generated by Django 5.0.1 on 2024-01-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_remove_partie_joueurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartieJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_inscription', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.joueur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.partie')),
            ],
        ),
        migrations.AddField(
            model_name='partie',
            name='joueurs',
            field=models.ManyToManyField(through='battle.PartieJoueur', to='battle.joueur'),
        ),
    ]
