# Generated by Django 5.0.1 on 2024-02-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_statutpartie'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='battle.statutpartie'),
        ),
    ]
