# Generated by Django 5.0.1 on 2024-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_remove_partiejoueur_is_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='TypeJeux',
        ),
    ]
