# Generated by Django 5.0.1 on 2024-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_partiejoueur_partie_joueurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cartes',
            field=models.ManyToManyField(to='battle.carte'),
        ),
        migrations.AddField(
            model_name='partie',
            name='decks',
            field=models.ManyToManyField(to='battle.deck'),
        ),
    ]
