# Generated by Django 5.0.1 on 2024-02-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_alter_partie_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='battle.statutpartie'),
        ),
    ]
