# Generated by Django 5.0.1 on 2024-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_deck_cartes_partie_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiejoueur',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
