# Generated by Django 5.0.1 on 2024-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_alter_joueur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='profil_image_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
