# Generated by Django 5.0.1 on 2024-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_alter_partie_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='typejeux',
            name='nombre_joueur',
            field=models.IntegerField(default=6),
        ),
    ]
