# Generated by Django 5.0.1 on 2024-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_deck_joueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='moteur_de_jeu',
        ),
        migrations.AddField(
            model_name='carte',
            name='moteur_de_jeu',
            field=models.ManyToManyField(to='battle.moteurdejeu'),
        ),
    ]
