# Generated by Django 5.0.1 on 2024-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_joueur_profil_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='profil_image_path',
            field=models.CharField(default='https://cdn.jsdelivr.net/gh/Reeflex-M/cdn-carte@master/Profil-picture/19.png', max_length=200),
        ),
    ]
