# Generated by Django 5.0.1 on 2024-02-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_alter_joueur_profil_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='pseudo',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
