# Generated by Django 5.0.1 on 2024-01-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_remove_carte_moteur_de_jeu_carte_moteur_de_jeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='image_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
