# Generated by Django 5.0.1 on 2024-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_carte_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='image_path',
            new_name='front_image_path',
        ),
        migrations.AddField(
            model_name='carte',
            name='back_image_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
