# Generated by Django 5.0.1 on 2024-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_joueur_pseudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='gestionnaire_tour_id',
            field=models.IntegerField(default=0),
        ),
    ]
