# Generated by Django 5.0.1 on 2024-02-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_rename_typejeux_partie_type_jeu_alter_partie_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='puissance',
            field=models.IntegerField(null=True),
        ),
    ]
