# Generated by Django 5.0.1 on 2024-02-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_carte_puissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='joueur_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties_actuelles', to='battle.joueur'),
        ),
    ]
