# Generated by Django 5.0.1 on 2024-01-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_typejeux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typejeux',
            old_name='lien_image',
            new_name='path_splash',
        ),
    ]
