# Generated by Django 5.0.1 on 2024-01-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_remove_carte_moteur_de_jeu_carte_typejeux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='type_jeu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.typejeux'),
        ),
    ]
